# Generated by Django 4.2 on 2024-10-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tempuser",
            name="bio",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="tempuser",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tempuser",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "남성"), ("F", "여성"), ("O", "기타")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tempuser",
            name="nickname",
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="static/images/default_user.png",
                null=True,
                upload_to="static/images",
                verbose_name="프로필 사진",
            ),
        ),
    ]
